### ISSUE TITLE
I want to add new planes

### ISSUE THREAD

**Issue by TheKingJo** [jaihysc/Factorio-AircraftRealism#12]
Hi there,

I got this mod recommended by a friend and tried it out. I really like it. I also saw potential for adding more planes. I've already made a ton vehicle mods (https://mods.factorio.com/user/thekingjo) and now tried to make a Ju-87. I opened a thread on your mod page but later saw that you stated that github issues are looked at more often. So here's my question again:

I'm currently working on a Ju-87 for this mod. Would you implement it when I give you the relevant code additions?
Here's a screenshot of the plane ingame: https://steamcommunity.com/sharedfiles/filedetails/?id=2524507555

As I plan on making even more planes, would you consider adding me as collaborator? I'll always release my planes in a standalone mod and add code in your mod, always using _if mods[XYZ]_ to check for them.

**Comment by jaihysc** [comment]
I am planning on making some sort of system for adding new planes. With that implemented it would be easy to add additional planes in the future without having to modify my mod each time.

**Comment by TheKingJo** [comment]
Tell me if you need help/ideas. Am looking forward to this.

**Comment by jaihysc** [comment]
I pushed the new system to the 1.3 branch for you to try out.
Documentation is available in `Docs/`
If you need an example, I ported the existing planes to use the new system in `support_aircraft/`

Let me know if you need any clarification.

**Comment by jaihysc** [comment]
I wrote another example as a functional standalone mod in `Docs/FlyingCar_0.1.0` which converts the vanilla car into a flying one.

**Comment by TheKingJo** [comment]
Good work. I've adapted my mods data-final-fixes.lua according to your template and it works as intended. Just two more things:
1. How about giving all registered airplanes an unique collision_mask? Atleast for the grounded variants. I've used this function to give my Ju-87 a new collision_mask so it does only collide with other Ju's:
```
function find_unused_layer()
	local unused_layers = {}
	for i = 13, 55, 1 do
		unused_layers[i-12] = "layer-"..i
	end
	for i,data_type in pairs(data.raw) do
		for j,data_obj in pairs(data_type) do
			for k,layer in pairs(data_obj.collision_mask or {}) do
				for l,unused_layer in pairs(unused_layers) do
					if layer == unused_layer then
						unused_layers[l] = nil
					end
				end
			end
		end
	end
	for _,layer in pairs(unused_layers) do
		return layer
	end
	return nil
end
```
2. Are you thinking about making the airborne variant have no shadow? If yes, I used this function to disable them:
```
function emptyLayer(data)
	local layer
	layer = {
		width = 1,
		height = 1,
		frame_count = data.frame_count,
		direction_count = data.direction_count,
                animation_speed = data.animation_speed,
                max_advance = data.max_advance,
		filename = "__AircraftRealism__/graphics/empty128.png"
	}
end

function findChadows(entity)
	for i,value in ipairs(entity.animation.layers) do
		if value.draw_as_shadow == true then
			entity.animation.layers[i] = emptyLayer(value)
		end
	end
end
```
empty128.png is a 128x128 png with all pixels beeing transparent.

**Comment by jaihysc** [comment]
Addressing your points:

1. The player decides whether or not they want the airborne variant to have a shadow - this is from an existing setting option from previous versions. I added the ability to determine its value with `noAerialShadow`. If true, you can run your function to remove shadows from your planes.

2. You can zero `terrain_friction_modifier` with the prototype returned from `makeAirborne` yourself. I prefer to modify as little prototype variables as I can to give others flexiability.

**Comment by TheKingJo** [comment]
Aight.

Could you make it so that the `Aircraft` mod is optional? E.g. if I wanted to only use my own planes with your mod then I'd still get the other ones which I actually don't want.

**Comment by jaihysc** [comment]
Sounds good, Aircraft has been made optional

**Comment by TheKingJo** [comment]
Nice!

Is there anything left to test? When it's finalized and ready to publish you can give me a sign and I'll do you a German locale if you want.

**Comment by jaihysc** [comment]
I have given it a test and it seems all good. I can accept a pull request for your German locale, then it can be published.
